#pragma once
#include <functional>
#include <string>
#include <windows.h>

std::string WStringToString(const std::wstring& wstr);
std::wstring StringToWString(const std::string& str);
void LogToFile(const std::string& message);
void ShowMessageAndExit();
bool CheckIsDebuggerPresentDirect();
bool CheckDebugObject();
bool CheckRemoteDebugger();
bool CheckDebugPort();
bool CheckNtGlobalFlag();
bool CheckHeapFlags();
bool CheckProcessDebugFlags();
bool CheckParentProcess();
bool CheckOutputDebugStringAdvanced();
bool CheckSoftwareBreakpointsAdvanced();
bool CheckHardwareBreakpointsAdvanced();
bool CheckAssemblyInstructions();
bool CheckExceptions();
bool CheckTimingAdvanced();
bool CheckForDebuggerProcesses();
bool CheckForDebuggerStrings();
bool CheckForActiveDebuggerWindows();
bool CheckForDebuggerDrivers();
bool CheckForFunctionHooks();
bool CheckForInjectedModules();
bool CheckForVirtualProtectAbuse();
bool CheckForExplorerDebuggerFolder();
bool CheckGlobalFlagsClearInProcess();
bool CheckGlobalFlagsClearInFile();
bool CheckForDebuggerRegistryKeys();
bool CheckForIFEODebugger();
bool CheckNoDebugInherit();
bool CheckExceptionCount();
bool CheckForAnalysisToolsViaWMI();
bool CheckForSystemCallHooks();
bool CheckForThreadHiding();
bool CheckForModuleHiding();
bool CheckForMemoryPatches();
bool CheckForFileSystemRedirection();
bool CheckForDriverSignatureEnforcement();
bool CheckForTestSigningMode();
bool CheckForUnsignedDrivers();
bool CheckForDriverHiding();
bool CheckForDriverHooks();
bool CheckForDriverInjection();
bool CheckForAPCInjection();
bool CheckForHookInjection();
bool CheckForRemoteThreadInjection();
bool CheckThreadIntegrity(HANDLE hThread);
void HideThread(HANDLE hThread);
bool IsDebuggerPresentCustom();
bool CheckForHardwareBreakpoints();
bool CheckForSoftwareBreakpoints();
bool CheckForTimingAttacks();
std::string GetCurrentProcessName();
bool IsRandomizedName(const std::string& name);
std::string GenerateRandomExeName();
std::string GenerateRandomBatName();
void RandomizeProcessName();
bool CheckForSuspiciousFilesInDirectory();
void ClearActivityTraces();
bool CheckSessionWithServer(const std::string& sessionid);
void InitializeAntiInject(const std::string& key);
void InitializeAntiDebug();
void CleanupAntiDebug();
void InitializeDllLoadMonitoring();
void CleanupDllLoadMonitoring();
DWORD WINAPI AntiInjectThread(LPVOID lpParam);
DWORD WINAPI CheckSuspiciousFilesThread(LPVOID lpParam);
DWORD WINAPI DebuggerCheckThread(LPVOID lpParam);
DWORD WINAPI MemoryIntegrityThread(LPVOID lpParam);
void PeriodicAntiDebugCheck(const std::string& key);
bool PerformAntiDebugChecks();
bool CheckMemoryIntegrity();
void InitializeMemoryIntegrityCheck(void* baseAddress, SIZE_T regionSize);
void CleanupMemoryIntegrity();